#
#./build.sh ipcp_isca2020 bingo_dpc3 14
#./build.sh ipcp_isca2020 spp  14
#./build.sh ipcp_isca2020 ip_stride  14
#./build.sh vberti spp  14
#./build.sh vberti bingo_dpc3  14
#./build.sh vberti ip_stride  14
#./build.sh mlop_dpc3 ip_stride  14
#./build.sh mlop_dpc3 spp  14
#./build.sh mlop_dpc3 bingo_dpc3  14
#./build.sh ip_stride bingo_dpc3  14
#./build.sh ip_stride spp  14
#./build.sh ipcp_isca2020 no 14
#./build.sh mlop_dpc3 no  14
#./build.sh vberti no  14
#./build.sh ip_stride no  14
#./build.sh no spp  14
#./build.sh no bingo_dpc3   14
#./build.sh no ip_stride  14
#./build.sh no no 14

./build.sh no no 1
./build.sh no no 2
./build.sh no no 3
./build.sh no no 4
./build.sh no no 5
./build.sh no no 6
./build.sh no no 7
./build.sh no no 8
./build.sh no no 9
./build.sh no no 10
./build.sh no no 11
./build.sh no no 12
./build.sh no no 13
./build.sh no no 14