./run_all_combination_gap.sh ipcp_isca2020 ppf pref_l1_l2 ipcp_ppf  20
./run_all_combination_gap.sh ipcp_isca2020 bingo_dpc3 pref_l1_l2 ipcp_bingo  20
./run_all_combination_gap.sh ipcp_isca2020 spp pref_l1_l2 ipcp_spp  20
./run_all_combination_gap.sh ipcp_isca2020 ip_stride pref_l1_l2 ipcp_ipstride  20
./run_all_combination_gap.sh vberti ppf pref_l1_l2 vberti_ppf  20
./run_all_combination_gap.sh vberti spp pref_l1_l2 vberti_spp  20
./run_all_combination_gap.sh vberti bingo_dpc3 pref_l1_l2 vberti_bingo  20
./run_all_combination_gap.sh vberti ip_stride pref_l1_l2 vberti_ipstride  20
./run_all_combination_gap.sh mlop_dpc3 ip_stride pref_l1_l2  mlop_ipstride  20
./run_all_combination_gap.sh mlop_dpc3 ppf pref_l1_l2  mlop_ppf  20
./run_all_combination_gap.sh mlop_dpc3 spp pref_l1_l2  mlop_spp  20                   
./run_all_combination_gap.sh mlop_dpc3 bingo_dpc3 pref_l1_l2  mlop_bingo  20
./run_all_combination_gap.sh ip_stride ppf pref_l1_l2 ipstride_ppf  20
./run_all_combination_gap.sh ip_stride bingo_dpc3 pref_l1_l2 ipstride_bingo  20
./run_all_combination_gap.sh ip_stride spp pref_l1_l2 ipstride_spp  20 
./run_all_combination_gap.sh ipcp_isca202 no pref_l1 ipcp  20
./run_all_combination_gap.sh mlop_dpc3 no pref_l1 mlop  20
./run_all_combination_gap.sh vberti no pref_l1 vberti  20
./run_all_combination_gap.sh ip_stride no pref_l1 ipStride  20
./run_all_combination_gap.sh no spp pref_l2 spp  20
./run_all_combination_gap.sh no bingo_dpc3  pref_l2 bingo 20
./run_all_combination_gap.sh no ppf pref_l2 spp_ppf  20
./run_all_combination_gap.sh no ip_stride pref_l2 ipStride  20